// src/app.tsx
import { Box, CircularProgress, Paper, Stack } from "@mui/material";
import "./app.css";
import { Track } from "./components/track";
import { Player } from "./components/player";
import { useAudio } from "./lib/hooks/use-audio.hook";

const baseUrl = "audio/";
const audioFileNames = [
  "Drums.mp3",
  "Bass.mp3",
  "Instruments.mp3",
  "Vocal.mp3",
  // "Verb.mp3",
  // "Vocal_Verb.mp3",
];

const audioFileUrls = audioFileNames.map(
  (audioFileName) => baseUrl + audioFileName
);

function App() {
  const { isReady, start, stop, setVolume } = useAudio(audioFileUrls);

  return isReady ? (
    <Paper sx={{ padding: 2 }}>
      <Stack direction="column">
        <Player onStart={start} onStop={stop} />
        <Stack direction="row" spacing={2}>
          {audioFileUrls.map((audioFileUrl, trackIndex) => (
            <Track
              key={audioFileUrl}
              trackIndex={trackIndex}
              onVolumeChange={setVolume}
              minDb={-40}
              maxDb={10}
            />
          ))}
        </Stack>
      </Stack>
    </Paper>
  ) : (
    <Box sx={{ display: "flex" }} margin={2}>
      <Stack direction="row" alignItems="center">
        <CircularProgress />
        <Box margin={2}>Loading...</Box>
      </Stack>
    </Box>
  );
}

export default App;

// vue/src/app.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import Player from "./components/player.vue";
import Track from "./components/track.vue";
import { useAudio } from "./composables/use-audio";
import { getFileNameWithoutExtension } from "./utils/file.util";

const baseUrl = "audio/";

const audioFileNames = ref([
  "drums.mp3",
  "bassguitar.mp3",
  "clav.mp3",
  "leadguitar.mp3",
  "horns.mp3",
]);

const audioFileUrls = computed(() =>
  audioFileNames.value.map((audioFileName) => baseUrl + audioFileName)
);

const { isReady, setVolume, start, stop } = useAudio(audioFileUrls);
</script>

<template>
  <div v-if="isReady">
    <Player @start="start" @stop="stop" />
    <div class="container__track">
      <div
        v-for="(audioFileUrl, trackIndex) in audioFileUrls"
        :key="audioFileUrl"
      >
        <Track
          :trackLabel="getFileNameWithoutExtension(audioFileNames[trackIndex])"
          :trackIndex="trackIndex"
          :minDb="-40"
          :maxDb="10"
        />
      </div>
    </div>
  </div>
  <div v-else>Loading...</div>
</template>

<style scoped>
.container__track {
  display: flex;
  flex-direction: row;
}
</style>
